Update vault scripts

diff --git a/bin/vault-backup b/bin/vault-backup
--- a/bin/vault-backup
+++ b/bin/vault-backup
@@ -2,29 +2,37 @@
 
 set -e
 
-tarsnap_bin=$(which tarsnap)
-if [ -z "$tarsnap_bin" ]; then
+mount_point=${1:-}
+
+if [ -z "$mount_point" ]; then
+    error_code=66
+    echo "Please pass the mount point as first parameter (error: $error_code)"
+    exit $error_code
+fi
+
+# convenience
+rebuild_cache=${2:false}
+
+TARSNAP=$(which tarsnap)
+if [ -z "$TARSNAP" ]; then
     echo "Tarsnap is not installed, see https://www.tarsnap.com/download.html"
     exit 1
 fi
 
-tarsnap_conf=$HOME/.backup/tarsnap.conf
-work_dir=/tmp
-root_dir=vault
+CONF=$HOME/.backup/vault.tarsnap
+ROOT_DIR=$mount_point
 
-$tarsnap_bin --verify-config $tarsnap_conf
+$TARSNAP --verify-config $CONF
 
-if [ "$1" = "--fsck" -o "$1" = "-f" -o "$1" = "--cache" ] ; then
+if [ "$rebuild_cache" = "true" ] ; then
     echo "Rebuilding tarsnap cache...";
-    $tarsnap_bin --fsck --configfile "$tarsnap_conf"
+    sudo $TARSNAP --fsck --configfile "$CONF";
 else
     echo "Performing tarsnap backup...";
-    $tarsnap_bin --configfile "$tarsnap_conf" \
-             -C "$work_dir" \
-             -c \
-             -v \
-             -f "$(uname -n)-$(date +%Y%m%d-%H%M%S)" \
-             "$root_dir";
+    sudo $TARSNAP \
+         --configfile "$CONF" \
+         -c \
+         -v \
+         -f "$(uname -n)-$(date +%Y%m%d-%H%M%S)" \
+         "$ROOT_DIR";
 fi
-
-cd -
diff --git a/bin/vault-mount b/bin/vault-mount
--- a/bin/vault-mount
+++ b/bin/vault-mount
@@ -3,7 +3,20 @@
 set -uo pipefail
 
 loop_file=${1:-}
-mount_point=/data/vault
+
+if [ -z "$loop_file" ]; then
+    error_code=65
+    echo "Please pass the vault file path as first parameter (error: $error_code)"
+    exit $error_code
+fi
+
+mount_point=${2:-}
+
+if [ -z "$mount_point" ]; then
+    error_code=66
+    echo "Please pass the mount point as second parameter (error: $error_code)"
+    exit $error_code
+fi
 
 dev_loop=""
 existing_loop=$(losetup -j "$loop_file")
diff --git a/bin/vault-umount b/bin/vault-umount
--- a/bin/vault-umount
+++ b/bin/vault-umount
@@ -2,8 +2,15 @@
 
 set -uo pipefail
 
-mount_point=/data/vault
-vault_bkp=$HOME/bin/vault-backup
+mount_point=${1:-}
+
+if [ -z "$mount_point" ]; then
+    error_code=66
+    echo "Please pass the mount point as second parameter (error: $error_code)"
+    exit $error_code
+fi
+
+vault_bkp_bin=$HOME/bin/vault-backup
 
 answer_timeout=10
 ANS="y"
@@ -18,11 +25,11 @@ if [[ "$(mount)" =~ /dev/mapper.*"$mount_point" ]]; then
         if [[ "$ans" =~ y|Y ]] ; then
             echo "Ok, skipping vault backup..."
         else
-           $vault_bkp
+           $vault_bkp_bin $mount_point
         fi
     else
         echo "No input received in $answer_timeout seconds, backing up..."
-        $vault_bkp
+        $vault_bkp_bin $mount_point
     fi
 fi
 
