Tweak echos of vault scripts

diff --git a/bin/vault-mount b/bin/vault-mount
--- a/bin/vault-mount
+++ b/bin/vault-mount
@@ -18,15 +18,16 @@ if [ -z "$mount_point" ]; then
     exit $error_code
 fi
 
+echo -n "Verifying digest for $loop_file..."
 pushd $(dirname $loop_file) > /dev/null
 md5sum --quiet --strict --check "$loop_file.md5"
 popd > /dev/null
 
 if [ "$?" -eq 0 ]; then
-    echo -e "Digest verification for $loop_file successful"
+    echo "Completed."
 else
     error_code=66
-    echo -e "Digest verification for $loop_file failed: aborting (error: $error_code)"
+    echo "Failed (error: $error_code)."
     exit $error_code
 fi
 
@@ -36,17 +37,17 @@ existing_loop=$(losetup -j "$loop_file")
 if [ -z "$existing_loop" ] ; then
     tmp_loop_dev=$(sudo losetup -f)
     if [ "$?" = 0 ]; then
-        echo -e "Mounting vault on $dev_loop..."
+        echo "Mounting vault on $dev_loop..."
         sudo losetup $tmp_loop_dev $loop_file
         if [ "$?" = 0 ]; then
             dev_loop=$tmp_loop_dev
         fi
     else
-        echo -e "Error: cannot retrieve temporary loop device"
+        echo "Error: cannot retrieve temporary loop device"
     fi
 else
     dev_loop=$(echo $existing_loop | awk -F":" '{ print($1) }')
-    echo -e "The file $loop_file is already mounted on $dev_loop";
+    echo "The file $loop_file is already mounted on $dev_loop";
 fi
 
 if [ -n "$dev_loop" ]; then
@@ -62,22 +63,22 @@ if [ -n "$dev_loop" ]; then
                 sudo mount /dev/mapper/vault $mount_point
 
                 if [ "$?" -eq 0 ]; then
-                    echo -e "Vault mounted on $mount_point"
+                    echo "Vault mounted on $mount_point"
                 else
-                    echo -e "Error: mount exited with $?"
+                    echo "Error: mount exited with $?"
                 fi
 
             else
-                echo -e "Error: cryptsetup exited with $?"
+                echo "Error: cryptsetup exited with $?"
             fi
         else
             echo "$luks_status"
         fi
     else
-        echo -e "Error: cannot retrieve vault status"
+        echo "Error: cannot retrieve vault status"
     fi
 else
-    echo -e "Error: cannot detect the mounted loop device"
+    echo "Error: cannot detect the mounted loop device"
 fi
 
 exit $?
diff --git a/bin/vault-umount b/bin/vault-umount
--- a/bin/vault-umount
+++ b/bin/vault-umount
@@ -12,21 +12,21 @@ fi
 
 # AR we don't backup the contents of the mounted vault anymore
 
-echo -e "Remove all executable flags..."
+echo "Remove all executable flags..."
 find $mount_point -type f \( -perm -u=x -o -perm -g=x -o -perm -o=x \) -exec sudo chmod -v -x {} ';'
 
-echo -e "Adjust file ownership..."
+echo "Adjust file ownership..."
 find $mount_point \! -user root -exec sudo chown -v root:vault {} ';'
 
-echo -e "Adjust group permissions..."
+echo "Adjust group permissions..."
 find $mount_point -type f -and -perm -o=rw -and \! -perm -g=rw -exec sudo chmod -v g+rw {} ';'
 find $mount_point -type d -and -perm -o=rwx -and \! -perm -g=rwx -exec sudo chmod -v g+rwx {} ';'
 
-echo -e "Unmounting vault from $mount_point..."
+echo "Unmounting vault from $mount_point..."
 sudo umount $mount_point
 
 if [ "$?" = "0" ]; then
-    echo -e "Encrypting back again..."
+    echo "Encrypting vault..."
     sudo cryptsetup luksClose vault
 
     if [ "$?" = "0" ]; then
@@ -34,23 +34,23 @@ if [ "$?" = "0" ]; then
         vault_file=$(echo "$vault_losetup" | grep -o '(.*)' | cut -d \( -f 2 | cut -d \) -f 1)
         dev_loop=$(echo "$vault_losetup" | awk -F ':' '{ print($1) }')
 
-        echo -e "Umounting $dev_loop..."
+        echo "Umounting $dev_loop..."
         sudo losetup -d $dev_loop
 
         if [ "$?" = "0" ]; then
-            echo -e "Generating $vault_file digest..."
+            echo -n "Generating $vault_file digest..."
             pushd $(dirname $vault_file) > /dev/null
             md5sum $(basename $vault_file) > $vault_file.md5
             popd > /dev/null
-            echo "Completed!"
+            echo "Completed."
         else
-            echo -e "Error: losetup -d exited with $?"
+            echo "Error: losetup -d exited with $?"
         fi
     else
-        echo -e "Error: cryptsetup exited with $?"
+        echo "Error: cryptsetup exited with $?"
     fi
 else
-    echo -e "Error: umount exited with $?"
+    echo "Error: umount exited with $?"
 fi
 
 exit $?
